// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// external module sky130_sram_1kbyte_1rw1r_32x256_8

module WishboneMultiLayerSnnShell(	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7
  input         clock,	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7
                reset,	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7
                wb_cyc,	// src/main/scala/WishboneMultiLayerSnnShell.scala:55:14
                wb_stb,	// src/main/scala/WishboneMultiLayerSnnShell.scala:55:14
                wb_we,	// src/main/scala/WishboneMultiLayerSnnShell.scala:55:14
  input  [31:0] wb_addr,	// src/main/scala/WishboneMultiLayerSnnShell.scala:55:14
                wb_din,	// src/main/scala/WishboneMultiLayerSnnShell.scala:55:14
  output [31:0] wb_dout,	// src/main/scala/WishboneMultiLayerSnnShell.scala:55:14
  input  [3:0]  wb_sel,	// src/main/scala/WishboneMultiLayerSnnShell.scala:55:14
  output        wb_ack,	// src/main/scala/WishboneMultiLayerSnnShell.scala:55:14
  output [3:0]  io_spikesOut,	// src/main/scala/WishboneMultiLayerSnnShell.scala:56:14
  output        core_start,	// src/main/scala/WishboneMultiLayerSnnShell.scala:59:16
  output [7:0]  core_spikesIn,	// src/main/scala/WishboneMultiLayerSnnShell.scala:59:16
  input         core_busy,	// src/main/scala/WishboneMultiLayerSnnShell.scala:59:16
                core_done,	// src/main/scala/WishboneMultiLayerSnnShell.scala:59:16
  input  [3:0]  core_spikesOut,	// src/main/scala/WishboneMultiLayerSnnShell.scala:59:16
  input  [1:0]  core_configNLayers,	// src/main/scala/WishboneMultiLayerSnnShell.scala:59:16
  input  [3:0]  core_configNInputs,	// src/main/scala/WishboneMultiLayerSnnShell.scala:59:16
                core_configNOutputs,	// src/main/scala/WishboneMultiLayerSnnShell.scala:59:16
  input         core_sram_csb,	// src/main/scala/WishboneMultiLayerSnnShell.scala:59:16
  input  [7:0]  core_sram_addr,	// src/main/scala/WishboneMultiLayerSnnShell.scala:59:16
  output [31:0] core_sram_dout	// src/main/scala/WishboneMultiLayerSnnShell.scala:59:16
);

  wire        startPulse;	// src/main/scala/WishboneMultiLayerSnnShell.scala:92:33, :133:17, :134:25, :135:22, :136:30
  wire [31:0] _ram_dout0;	// src/main/scala/WishboneMultiLayerSnnShell.scala:77:19
  reg  [7:0]  spikesInReg;	// src/main/scala/WishboneMultiLayerSnnShell.scala:90:29
  reg  [3:0]  spikesOutReg;	// src/main/scala/WishboneMultiLayerSnnShell.scala:91:29
  reg         doneFlag;	// src/main/scala/WishboneMultiLayerSnnShell.scala:93:29
  wire        snnActive = core_busy | startPulse;	// src/main/scala/WishboneMultiLayerSnnShell.scala:92:33, :99:29, :133:17, :134:25, :135:22, :136:30
  wire        wbActive = wb_cyc & wb_stb;	// src/main/scala/WishboneMultiLayerSnnShell.scala:102:29
  wire        wbWrite = wbActive & wb_we;	// src/main/scala/WishboneMultiLayerSnnShell.scala:102:29, :104:31
  wire        _GEN = wb_addr[3:2] == 2'h0;	// src/main/scala/WishboneMultiLayerSnnShell.scala:106:28, :117:27, :124:22
  reg  [31:0] casez_tmp;	// src/main/scala/WishboneMultiLayerSnnShell.scala:124:22, :125:27
  always_comb begin	// src/main/scala/WishboneMultiLayerSnnShell.scala:111:11, :124:22, :125:27, :126:27, :127:27, :128:27
    casez (wb_addr[3:2])	// src/main/scala/WishboneMultiLayerSnnShell.scala:106:28, :111:11, :124:22, :125:27, :126:27, :127:27, :128:27
      2'b00:
        casez_tmp = {30'h0, doneFlag, core_busy};	// src/main/scala/WishboneMultiLayerSnnShell.scala:93:29, :111:11, :124:22, :125:27, :126:27, :127:27, :128:27
      2'b01:
        casez_tmp = {24'h0, spikesInReg};	// src/main/scala/WishboneMultiLayerSnnShell.scala:90:29, :111:11, :124:22, :125:27, :126:27, :127:27, :128:27
      2'b10:
        casez_tmp = {28'h0, spikesOutReg};	// src/main/scala/WishboneMultiLayerSnnShell.scala:91:29, :111:11, :124:22, :125:27, :126:27, :127:27, :128:27
      default:
        casez_tmp =
          {16'h0,
           core_configNOutputs,
           4'h0,
           core_configNInputs,
           2'h0,
           core_configNLayers};	// src/main/scala/WishboneMultiLayerSnnShell.scala:91:29, :111:11, :113:23, :117:27, :124:22, :125:27, :126:27, :127:27, :128:27
    endcase	// src/main/scala/WishboneMultiLayerSnnShell.scala:106:28, :111:11, :124:22, :125:27, :126:27, :127:27, :128:27
  end // always_comb
  assign startPulse = wbWrite & ~(|(wb_addr[31:4])) & _GEN & wb_din[0];	// src/main/scala/WishboneMultiLayerSnnShell.scala:92:33, :104:31, :107:29, :124:22, :133:17, :134:{10,25}, :135:22, :136:{30,39}
  wire        _GEN_0 = wbActive & (|(wb_addr[31:4]));	// src/main/scala/WishboneMultiLayerSnnShell.scala:102:29, :107:29, :148:23
  wire        _GEN_1 = snnActive | ~_GEN_0;	// src/main/scala/WishboneMultiLayerSnnShell.scala:70:46, :99:29, :142:19, :146:15, :148:{23,40}, :150:15
  always @(posedge clock) begin	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7
    if (reset) begin	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7
      spikesInReg <= 8'h0;	// src/main/scala/WishboneMultiLayerSnnShell.scala:90:29
      spikesOutReg <= 4'h0;	// src/main/scala/WishboneMultiLayerSnnShell.scala:91:29
      doneFlag <= 1'h0;	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7, :93:29
    end
    else begin	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7
      if (~(wbWrite & ~(|(wb_addr[31:4]))) | _GEN | wb_addr[3:2] != 2'h1) begin	// src/main/scala/WishboneMultiLayerSnnShell.scala:90:29, :104:31, :106:28, :107:29, :124:22, :133:17, :134:{10,25}, :135:22
      end
      else	// src/main/scala/WishboneMultiLayerSnnShell.scala:90:29, :133:17, :134:25, :135:22
        spikesInReg <= wb_din[7:0];	// src/main/scala/WishboneMultiLayerSnnShell.scala:90:29, :137:40
      if (core_done)	// src/main/scala/WishboneMultiLayerSnnShell.scala:59:16
        spikesOutReg <= core_spikesOut;	// src/main/scala/WishboneMultiLayerSnnShell.scala:91:29
      doneFlag <= ~startPulse & (core_done | doneFlag);	// src/main/scala/WishboneMultiLayerSnnShell.scala:92:33, :93:29, :133:17, :134:25, :135:22, :136:30, :156:19, :158:18, :160:20, :161:14
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7
    initial begin	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7
        spikesInReg = _RANDOM[/*Zero width*/ 1'b0][7:0];	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7, :90:29
        spikesOutReg = _RANDOM[/*Zero width*/ 1'b0][11:8];	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7, :90:29, :91:29
        doneFlag = _RANDOM[/*Zero width*/ 1'b0][12];	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7, :90:29, :93:29
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  sky130_sram_1kbyte_1rw1r_32x256_8 ram (	// src/main/scala/WishboneMultiLayerSnnShell.scala:77:19
    .clk0   (clock),
    .csb0   (snnActive ? core_sram_csb : ~_GEN_0),	// src/main/scala/WishboneMultiLayerSnnShell.scala:69:46, :72:57, :99:29, :142:19, :143:15, :148:{23,40}, :149:15
    .web0   (snnActive | ~_GEN_0 | ~wb_we),	// src/main/scala/WishboneMultiLayerSnnShell.scala:69:46, :70:46, :72:57, :99:29, :142:19, :144:15, :148:{23,40}, :150:{15,21}
    .wmask0 (_GEN_1 ? 4'hF : wb_sel),	// src/main/scala/WishboneMultiLayerSnnShell.scala:71:46, :142:19, :146:15, :147:15, :148:40
    .addr0  (snnActive ? core_sram_addr : _GEN_0 ? wb_addr[9:2] - 8'h4 : 8'h0),	// src/main/scala/WishboneMultiLayerSnnShell.scala:72:57, :90:29, :99:29, :108:{28,35}, :142:19, :145:15, :148:{23,40}, :151:15
    .din0   (_GEN_1 ? 32'h0 : wb_din),	// src/main/scala/WishboneMultiLayerSnnShell.scala:59:16, :142:19, :146:15, :148:40
    .dout0  (_ram_dout0),
    .clk1   (clock),
    .csb1   (1'h1),	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7
    .addr1  (8'h0),	// src/main/scala/WishboneMultiLayerSnnShell.scala:90:29
    .dout1  (/* unused */)
  );
  assign wb_dout =
    wbActive & ~wb_we ? ((|(wb_addr[31:4])) ? _ram_dout0 : casez_tmp) : 32'h0;	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7, :59:16, :77:19, :102:29, :105:{31,34}, :107:29, :111:11, :120:16, :121:24, :122:15, :124:22, :125:27
  assign wb_ack = wbActive;	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7, :102:29
  assign io_spikesOut = spikesOutReg;	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7, :91:29
  assign core_start = startPulse;	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7, :92:33, :133:17, :134:25, :135:22, :136:30
  assign core_spikesIn = spikesInReg;	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7, :90:29
  assign core_sram_dout = _ram_dout0;	// src/main/scala/WishboneMultiLayerSnnShell.scala:41:7, :77:19
endmodule

module MultiLayerSnnFlex(	// src/main/scala/MultiLayerSnnFlex.scala:26:7
  input         clock,	// src/main/scala/MultiLayerSnnFlex.scala:26:7
                reset,	// src/main/scala/MultiLayerSnnFlex.scala:26:7
  input  [7:0]  io_spikesIn,	// src/main/scala/MultiLayerSnnFlex.scala:57:14
  output [3:0]  io_spikesOut,	// src/main/scala/MultiLayerSnnFlex.scala:57:14
  output [1:0]  io_configNLayers,	// src/main/scala/MultiLayerSnnFlex.scala:57:14
  output [3:0]  io_configNInputs,	// src/main/scala/MultiLayerSnnFlex.scala:57:14
                io_configNOutputs,	// src/main/scala/MultiLayerSnnFlex.scala:57:14
  input         io_start,	// src/main/scala/MultiLayerSnnFlex.scala:57:14
  output        io_busy,	// src/main/scala/MultiLayerSnnFlex.scala:57:14
                io_done,	// src/main/scala/MultiLayerSnnFlex.scala:57:14
                io_sram_csb,	// src/main/scala/MultiLayerSnnFlex.scala:57:14
  output [7:0]  io_sram_addr,	// src/main/scala/MultiLayerSnnFlex.scala:57:14
  input  [31:0] io_sram_dout	// src/main/scala/MultiLayerSnnFlex.scala:57:14
);

  reg  [2:0]  state;	// src/main/scala/MultiLayerSnnFlex.scala:71:30
  reg         layerIdx;	// src/main/scala/MultiLayerSnnFlex.scala:72:30
  reg  [1:0]  groupIdx;	// src/main/scala/MultiLayerSnnFlex.scala:73:30
  reg  [3:0]  inputIdx;	// src/main/scala/MultiLayerSnnFlex.scala:74:30
  reg  [1:0]  configReadIdx;	// src/main/scala/MultiLayerSnnFlex.scala:75:30
  reg  [7:0]  spikesBuf;	// src/main/scala/MultiLayerSnnFlex.scala:78:29
  reg  [3:0]  spikesOutReg;	// src/main/scala/MultiLayerSnnFlex.scala:79:29
  reg  [15:0] accum_0;	// src/main/scala/MultiLayerSnnFlex.scala:82:22
  reg  [15:0] accum_1;	// src/main/scala/MultiLayerSnnFlex.scala:82:22
  reg  [15:0] accum_2;	// src/main/scala/MultiLayerSnnFlex.scala:82:22
  reg  [15:0] accum_3;	// src/main/scala/MultiLayerSnnFlex.scala:82:22
  reg  [7:0]  layerSpikes;	// src/main/scala/MultiLayerSnnFlex.scala:85:28
  reg  [1:0]  runtimeNLayers;	// src/main/scala/MultiLayerSnnFlex.scala:88:31
  reg  [3:0]  runtimeLayerSizes_0;	// src/main/scala/MultiLayerSnnFlex.scala:89:34
  reg  [3:0]  runtimeLayerSizes_1;	// src/main/scala/MultiLayerSnnFlex.scala:89:34
  reg  [3:0]  runtimeLayerSizes_2;	// src/main/scala/MultiLayerSnnFlex.scala:89:34
  reg  [3:0]  runtimeLayerInputs_0;	// src/main/scala/MultiLayerSnnFlex.scala:90:35
  reg  [3:0]  runtimeLayerInputs_1;	// src/main/scala/MultiLayerSnnFlex.scala:90:35
  reg  [3:0]  runtimeLayerOutputs_0;	// src/main/scala/MultiLayerSnnFlex.scala:91:36
  reg  [3:0]  runtimeLayerOutputs_1;	// src/main/scala/MultiLayerSnnFlex.scala:91:36
  reg  [1:0]  runtimeLayerGroups_0;	// src/main/scala/MultiLayerSnnFlex.scala:92:35
  reg  [1:0]  runtimeLayerGroups_1;	// src/main/scala/MultiLayerSnnFlex.scala:92:35
  reg  [7:0]  runtimeLayerBases_0;	// src/main/scala/MultiLayerSnnFlex.scala:93:34
  reg  [7:0]  runtimeLayerBases_1;	// src/main/scala/MultiLayerSnnFlex.scala:93:34
  reg  [3:0]  previousLayerSize;	// src/main/scala/MultiLayerSnnFlex.scala:94:34
  reg  [7:0]  firstWeightBase;	// src/main/scala/MultiLayerSnnFlex.scala:95:32
  reg  [7:0]  nextWeightBase;	// src/main/scala/MultiLayerSnnFlex.scala:96:31
  wire        _GEN = state == 3'h0;	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :71:30, :132:17
  wire        _GEN_0 = state == 3'h1;	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :71:30, :132:17
  wire        _GEN_1 = configReadIdx == 2'h0;	// src/main/scala/MultiLayerSnnFlex.scala:73:30, :75:30, :154:26
  wire        _GEN_2 = configReadIdx == runtimeNLayers + 2'h1;	// src/main/scala/MultiLayerSnnFlex.scala:75:30, :88:31, :190:69, :192:28
  wire        _GEN_3 = _GEN_1 | ~_GEN_2;	// src/main/scala/MultiLayerSnnFlex.scala:72:30, :154:{26,35}, :192:{28,47}, :193:23
  wire [1:0]  _nextConfigIdx_T = configReadIdx + 2'h1;	// src/main/scala/MultiLayerSnnFlex.scala:75:30, :190:69, :202:45
  wire        _GEN_4 = state == 3'h2;	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :71:30, :132:17
  wire        _GEN_5 =
    inputIdx == ((layerIdx ? 4'h0 : runtimeLayerInputs_0)
                 | (layerIdx ? runtimeLayerInputs_1 : 4'h0)) - 4'h1;	// src/main/scala/MultiLayerSnnFlex.scala:72:30, :74:30, :90:35, :230:{21,32}, src/main/scala/chisel3/util/Mux.scala:30:73
  wire [3:0]  _nextInput_T = inputIdx + 4'h1;	// src/main/scala/MultiLayerSnnFlex.scala:74:30, :105:54, :233:34
  wire        _GEN_6 = state == 3'h3;	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :71:30, :132:17
  wire        _GEN_7 = state == 3'h4;	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :71:30, :132:17
  wire        _GEN_8 =
    groupIdx == ((layerIdx ? 2'h0 : runtimeLayerGroups_0)
                 | (layerIdx ? runtimeLayerGroups_1 : 2'h0)) - 2'h1;	// src/main/scala/MultiLayerSnnFlex.scala:72:30, :73:30, :92:35, :267:{21,36}, src/main/scala/chisel3/util/Mux.scala:30:73
  wire        _GEN_9 = {1'h0, layerIdx} == runtimeNLayers - 2'h1;	// src/main/scala/MultiLayerSnnFlex.scala:72:30, :88:31, :269:{23,42}
  wire        _GEN_10 = _GEN_8 & _GEN_9;	// src/main/scala/MultiLayerSnnFlex.scala:79:29, :267:{21,43}, :269:{23,49}, :270:24
  wire        _nextLayer_T = layerIdx - 1'h1;	// src/main/scala/MultiLayerSnnFlex.scala:72:30, :274:36
  wire [1:0]  _nextGroup_T = groupIdx + 2'h1;	// src/main/scala/MultiLayerSnnFlex.scala:73:30, :190:69, :286:34
  reg  [2:0]  casez_tmp;	// src/main/scala/MultiLayerSnnFlex.scala:132:17, :134:22
  always_comb begin	// src/main/scala/MultiLayerSnnFlex.scala:71:30, :132:17, :134:22, :154:35, :230:39, :261:13, :267:43, :299:15
    casez (state)	// src/main/scala/MultiLayerSnnFlex.scala:71:30, :132:17, :134:22, :154:35, :230:39, :261:13, :267:43, :299:15
      3'b000:
        casez_tmp = io_start ? 3'h1 : state;	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :71:30, :132:17, :134:22, :147:15, :154:35, :230:39, :261:13, :267:43, :299:15
      3'b001:
        casez_tmp = _GEN_3 ? state : 3'h2;	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :71:30, :72:30, :132:17, :134:22, :154:35, :192:47, :230:39, :261:13, :267:43, :299:15
      3'b010:
        casez_tmp = _GEN_5 ? 3'h3 : state;	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :71:30, :132:17, :134:22, :154:35, :230:{21,39}, :231:15, :261:13, :267:43, :299:15
      3'b011:
        casez_tmp = 3'h4;	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :71:30, :132:17, :134:22, :154:35, :230:39, :261:13, :267:43, :299:15
      3'b100:
        casez_tmp = _GEN_10 ? 3'h5 : 3'h2;	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :71:30, :79:29, :132:17, :134:22, :154:35, :230:39, :261:13, :267:43, :269:49, :270:24, :271:17, :283:17, :293:15, :299:15
      3'b101:
        casez_tmp = 3'h0;	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :71:30, :132:17, :134:22, :154:35, :230:39, :261:13, :267:43, :299:15
      3'b110:
        casez_tmp = state;	// src/main/scala/MultiLayerSnnFlex.scala:71:30, :132:17, :134:22, :154:35, :230:39, :261:13, :267:43, :299:15
      default:
        casez_tmp = state;	// src/main/scala/MultiLayerSnnFlex.scala:71:30, :132:17, :134:22, :154:35, :230:39, :261:13, :267:43, :299:15
    endcase	// src/main/scala/MultiLayerSnnFlex.scala:71:30, :132:17, :134:22, :154:35, :230:39, :261:13, :267:43, :299:15
  end // always_comb
  wire [3:0]  curNOut =
    (layerIdx ? 4'h0 : runtimeLayerOutputs_0) | (layerIdx ? runtimeLayerOutputs_1 : 4'h0);	// src/main/scala/MultiLayerSnnFlex.scala:72:30, :74:30, :91:36, src/main/scala/chisel3/util/Mux.scala:30:73
  wire        _GEN_11 =
    inputIdx == 4'h0 & spikesBuf[0] | inputIdx == 4'h1 & spikesBuf[1] | inputIdx == 4'h2
    & spikesBuf[2] | inputIdx == 4'h3 & spikesBuf[3] | inputIdx == 4'h4 & spikesBuf[4]
    | inputIdx == 4'h5 & spikesBuf[5] | inputIdx == 4'h6 & spikesBuf[6] | inputIdx == 4'h7
    & spikesBuf[7];	// src/main/scala/MultiLayerSnnFlex.scala:74:30, :78:29, :105:{54,75}, src/main/scala/chisel3/util/Mux.scala:30:73
  wire [3:0]  curNOut_1 =
    (layerIdx ? 4'h0 : runtimeLayerOutputs_0) | (layerIdx ? runtimeLayerOutputs_1 : 4'h0);	// src/main/scala/MultiLayerSnnFlex.scala:72:30, :74:30, :91:36, src/main/scala/chisel3/util/Mux.scala:30:73
  wire [2:0]  _GEN_12 = {1'h0, groupIdx};	// src/main/scala/MultiLayerSnnFlex.scala:72:30, :73:30, :216:19
  wire [4:0]  _GEN_13 = {1'h0, groupIdx, 2'h0};	// src/main/scala/MultiLayerSnnFlex.scala:72:30, :73:30, :217:17
  wire [4:0]  neuronsInGroup =
    {1'h0, _GEN_12 + 3'h1, 2'h0} > {2'h0, curNOut} ? {1'h0, curNOut} - _GEN_13 : 5'h4;	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :72:30, :73:30, :215:31, :216:{19,27,33}, :217:17, src/main/scala/chisel3/util/Mux.scala:30:73
  wire [4:0]  neuronsInGroup_1 =
    {1'h0, _GEN_12 + 3'h1, 2'h0} > {2'h0, curNOut_1} ? {1'h0, curNOut_1} - _GEN_13 : 5'h4;	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :72:30, :73:30, :215:31, :216:19, :217:17, :244:31, :245:{19,27,33}, :246:17, src/main/scala/chisel3/util/Mux.scala:30:73
  wire [31:0] _mask_T = 32'h1 << neuronsInGroup_1;	// src/main/scala/MultiLayerSnnFlex.scala:244:31, :258:37
  wire [38:0] _layerSpikes_T_1 =
    {35'h0,
     _mask_T[3:0] - 4'h1
       & {(|(neuronsInGroup_1[4:2])) & $signed(accum_3) > 16'sh3F,
          neuronsInGroup_1 > 5'h2 & $signed(accum_2) > 16'sh3F,
          (|(neuronsInGroup_1[4:1])) & $signed(accum_1) > 16'sh3F,
          (|neuronsInGroup_1) & $signed(accum_0) > 16'sh3F}} << {35'h0, groupIdx, 2'h0};	// src/main/scala/MultiLayerSnnFlex.scala:73:30, :82:22, :225:18, :244:31, :253:{29,46,58}, :255:33, :258:{29,37,56}, :259:42
  wire [7:0]  _headerBase_T_1 = {6'h0, io_sram_dout[1:0]} + 8'h2;	// src/main/scala/MultiLayerSnnFlex.scala:155:41, :157:{40,56}, :205:24
  wire        _GEN_14 = _GEN_4 | _GEN_6;	// src/main/scala/MultiLayerSnnFlex.scala:79:29, :132:17
  wire        _GEN_15 = _GEN_0 | _GEN_14;	// src/main/scala/MultiLayerSnnFlex.scala:79:29, :132:17
  wire        _GEN_16 = _GEN_7 & _GEN_8;	// src/main/scala/MultiLayerSnnFlex.scala:78:29, :132:17, :267:{21,43}, :269:49
  wire [1:0]  _sizeEntryIdx_T = configReadIdx - 2'h1;	// src/main/scala/MultiLayerSnnFlex.scala:75:30, :166:42
  wire [1:0]  _completedLayerIdx_T = configReadIdx - 2'h2;	// src/main/scala/MultiLayerSnnFlex.scala:75:30, :174:49
  wire [3:0]  _groups_T = io_sram_dout[3:0] + 4'h3;	// src/main/scala/MultiLayerSnnFlex.scala:105:54, :165:36, :175:35
  wire        _GEN_17 = configReadIdx == 2'h1;	// src/main/scala/MultiLayerSnnFlex.scala:75:30, :90:35, :173:{28,37}, :177:45, :190:69
  wire        _GEN_18 = _GEN_1 | _GEN_17;	// src/main/scala/MultiLayerSnnFlex.scala:90:35, :154:{26,35}, :173:{28,37}, :177:45
  wire        _GEN_19 = _GEN | ~_GEN_0 | _GEN_18 | (|_completedLayerIdx_T);	// src/main/scala/MultiLayerSnnFlex.scala:89:34, :90:35, :132:17, :154:35, :173:{28,37}, :174:49, :177:{36,45}
  wire        _GEN_20 = _GEN | ~_GEN_0 | _GEN_18 | _completedLayerIdx_T != 2'h1;	// src/main/scala/MultiLayerSnnFlex.scala:89:34, :90:35, :132:17, :154:35, :173:{28,37}, :174:49, :177:{36,45}, :190:69
  always @(posedge clock) begin	// src/main/scala/MultiLayerSnnFlex.scala:26:7
    if (reset) begin	// src/main/scala/MultiLayerSnnFlex.scala:26:7
      state <= 3'h0;	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :71:30
      layerIdx <= 1'h0;	// src/main/scala/MultiLayerSnnFlex.scala:72:30
      groupIdx <= 2'h0;	// src/main/scala/MultiLayerSnnFlex.scala:73:30
      inputIdx <= 4'h0;	// src/main/scala/MultiLayerSnnFlex.scala:74:30
      configReadIdx <= 2'h0;	// src/main/scala/MultiLayerSnnFlex.scala:73:30, :75:30
      spikesBuf <= 8'h0;	// src/main/scala/MultiLayerSnnFlex.scala:78:29
      spikesOutReg <= 4'h0;	// src/main/scala/MultiLayerSnnFlex.scala:74:30, :79:29
      accum_0 <= 16'h0;	// src/main/scala/MultiLayerSnnFlex.scala:82:{22,30}
      accum_1 <= 16'h0;	// src/main/scala/MultiLayerSnnFlex.scala:82:{22,30}
      accum_2 <= 16'h0;	// src/main/scala/MultiLayerSnnFlex.scala:82:{22,30}
      accum_3 <= 16'h0;	// src/main/scala/MultiLayerSnnFlex.scala:82:{22,30}
      layerSpikes <= 8'h0;	// src/main/scala/MultiLayerSnnFlex.scala:78:29, :85:28
      runtimeNLayers <= 2'h0;	// src/main/scala/MultiLayerSnnFlex.scala:73:30, :88:31
      runtimeLayerSizes_0 <= 4'h0;	// src/main/scala/MultiLayerSnnFlex.scala:74:30, :89:34
      runtimeLayerSizes_1 <= 4'h0;	// src/main/scala/MultiLayerSnnFlex.scala:74:30, :89:34
      runtimeLayerSizes_2 <= 4'h0;	// src/main/scala/MultiLayerSnnFlex.scala:74:30, :89:34
      runtimeLayerInputs_0 <= 4'h0;	// src/main/scala/MultiLayerSnnFlex.scala:74:30, :90:35
      runtimeLayerInputs_1 <= 4'h0;	// src/main/scala/MultiLayerSnnFlex.scala:74:30, :90:35
      runtimeLayerOutputs_0 <= 4'h0;	// src/main/scala/MultiLayerSnnFlex.scala:74:30, :91:36
      runtimeLayerOutputs_1 <= 4'h0;	// src/main/scala/MultiLayerSnnFlex.scala:74:30, :91:36
      runtimeLayerGroups_0 <= 2'h0;	// src/main/scala/MultiLayerSnnFlex.scala:73:30, :92:35
      runtimeLayerGroups_1 <= 2'h0;	// src/main/scala/MultiLayerSnnFlex.scala:73:30, :92:35
      runtimeLayerBases_0 <= 8'h0;	// src/main/scala/MultiLayerSnnFlex.scala:78:29, :93:34
      runtimeLayerBases_1 <= 8'h0;	// src/main/scala/MultiLayerSnnFlex.scala:78:29, :93:34
      previousLayerSize <= 4'h0;	// src/main/scala/MultiLayerSnnFlex.scala:74:30, :94:34
      firstWeightBase <= 8'h0;	// src/main/scala/MultiLayerSnnFlex.scala:78:29, :95:32
      nextWeightBase <= 8'h0;	// src/main/scala/MultiLayerSnnFlex.scala:78:29, :96:31
    end
    else begin	// src/main/scala/MultiLayerSnnFlex.scala:26:7
      state <= casez_tmp;	// src/main/scala/MultiLayerSnnFlex.scala:71:30, :132:17, :134:22
      if (_GEN) begin	// src/main/scala/MultiLayerSnnFlex.scala:132:17
        layerIdx <= ~io_start & layerIdx;	// src/main/scala/MultiLayerSnnFlex.scala:72:30, :134:22, :142:24
        if (io_start) begin	// src/main/scala/MultiLayerSnnFlex.scala:57:14
          groupIdx <= 2'h0;	// src/main/scala/MultiLayerSnnFlex.scala:73:30
          inputIdx <= 4'h0;	// src/main/scala/MultiLayerSnnFlex.scala:74:30
          configReadIdx <= 2'h0;	// src/main/scala/MultiLayerSnnFlex.scala:73:30, :75:30
          spikesBuf <= io_spikesIn;	// src/main/scala/MultiLayerSnnFlex.scala:78:29
          spikesOutReg <= 4'h0;	// src/main/scala/MultiLayerSnnFlex.scala:74:30, :79:29
          accum_0 <= 16'h0;	// src/main/scala/MultiLayerSnnFlex.scala:82:{22,30}
          accum_1 <= 16'h0;	// src/main/scala/MultiLayerSnnFlex.scala:82:{22,30}
          accum_2 <= 16'h0;	// src/main/scala/MultiLayerSnnFlex.scala:82:{22,30}
          accum_3 <= 16'h0;	// src/main/scala/MultiLayerSnnFlex.scala:82:{22,30}
          layerSpikes <= 8'h0;	// src/main/scala/MultiLayerSnnFlex.scala:78:29, :85:28
          runtimeNLayers <= 2'h0;	// src/main/scala/MultiLayerSnnFlex.scala:73:30, :88:31
          previousLayerSize <= 4'h0;	// src/main/scala/MultiLayerSnnFlex.scala:74:30, :94:34
          firstWeightBase <= 8'h0;	// src/main/scala/MultiLayerSnnFlex.scala:78:29, :95:32
          nextWeightBase <= 8'h0;	// src/main/scala/MultiLayerSnnFlex.scala:78:29, :96:31
        end
      end
      else begin	// src/main/scala/MultiLayerSnnFlex.scala:132:17
        if (_GEN_0) begin	// src/main/scala/MultiLayerSnnFlex.scala:132:17
          layerIdx <= _GEN_3 & layerIdx;	// src/main/scala/MultiLayerSnnFlex.scala:72:30, :154:35, :192:47
          if (_GEN_3) begin	// src/main/scala/MultiLayerSnnFlex.scala:72:30, :74:30, :154:35, :192:47
          end
          else begin	// src/main/scala/MultiLayerSnnFlex.scala:74:30, :154:35, :192:47
            groupIdx <= 2'h0;	// src/main/scala/MultiLayerSnnFlex.scala:73:30
            inputIdx <= 4'h0;	// src/main/scala/MultiLayerSnnFlex.scala:74:30
          end
          if (_GEN_1) begin	// src/main/scala/MultiLayerSnnFlex.scala:154:26
            configReadIdx <= 2'h1;	// src/main/scala/MultiLayerSnnFlex.scala:75:30, :190:69
            nextWeightBase <= _headerBase_T_1;	// src/main/scala/MultiLayerSnnFlex.scala:96:31, :157:{40,56}
          end
          else begin	// src/main/scala/MultiLayerSnnFlex.scala:154:26
            if (~_GEN_2)	// src/main/scala/MultiLayerSnnFlex.scala:72:30, :192:{28,47}, :193:23
              configReadIdx <= _nextConfigIdx_T;	// src/main/scala/MultiLayerSnnFlex.scala:75:30, :202:45
            if (~_GEN_17)	// src/main/scala/MultiLayerSnnFlex.scala:90:35, :173:{28,37}, :177:45
              nextWeightBase <=
                nextWeightBase
                + {2'h0, {2'h0, previousLayerSize} * {4'h0, _groups_T[3:2]}};	// src/main/scala/MultiLayerSnnFlex.scala:73:30, :74:30, :94:34, :96:31, :175:{35,42}, :184:{44,64}
          end
          if (_GEN_3) begin	// src/main/scala/MultiLayerSnnFlex.scala:72:30, :85:28, :154:35, :192:47
          end
          else begin	// src/main/scala/MultiLayerSnnFlex.scala:85:28, :154:35, :192:47
            accum_0 <= 16'h0;	// src/main/scala/MultiLayerSnnFlex.scala:82:{22,30}
            accum_1 <= 16'h0;	// src/main/scala/MultiLayerSnnFlex.scala:82:{22,30}
            accum_2 <= 16'h0;	// src/main/scala/MultiLayerSnnFlex.scala:82:{22,30}
            accum_3 <= 16'h0;	// src/main/scala/MultiLayerSnnFlex.scala:82:{22,30}
            layerSpikes <= 8'h0;	// src/main/scala/MultiLayerSnnFlex.scala:78:29, :85:28
          end
        end
        else begin	// src/main/scala/MultiLayerSnnFlex.scala:132:17
          if (_GEN_14 | ~_GEN_16 | _GEN_9) begin	// src/main/scala/MultiLayerSnnFlex.scala:72:30, :78:29, :79:29, :132:17, :267:43, :269:{23,49}
          end
          else	// src/main/scala/MultiLayerSnnFlex.scala:72:30, :132:17
            layerIdx <= _nextLayer_T;	// src/main/scala/MultiLayerSnnFlex.scala:72:30, :274:36
          if (_GEN_14 | ~_GEN_7) begin	// src/main/scala/MultiLayerSnnFlex.scala:73:30, :79:29, :132:17
          end
          else if (_GEN_8) begin	// src/main/scala/MultiLayerSnnFlex.scala:267:21
            if (~_GEN_9)	// src/main/scala/MultiLayerSnnFlex.scala:269:23
              groupIdx <= 2'h0;	// src/main/scala/MultiLayerSnnFlex.scala:73:30
          end
          else	// src/main/scala/MultiLayerSnnFlex.scala:267:21
            groupIdx <= _nextGroup_T;	// src/main/scala/MultiLayerSnnFlex.scala:73:30, :286:34
          if (_GEN_4) begin	// src/main/scala/MultiLayerSnnFlex.scala:132:17
            if (~_GEN_5)	// src/main/scala/MultiLayerSnnFlex.scala:230:21
              inputIdx <= _nextInput_T;	// src/main/scala/MultiLayerSnnFlex.scala:74:30, :233:34
            if ((|neuronsInGroup) & _GEN_11)	// src/main/scala/MultiLayerSnnFlex.scala:215:31, :225:{18,35}, src/main/scala/chisel3/util/Mux.scala:30:73
              accum_0 <= {{8{io_sram_dout[7]}}, io_sram_dout[7:0]} + accum_0;	// src/main/scala/MultiLayerSnnFlex.scala:82:22, :223:32, :226:{32,45}
            if ((|(neuronsInGroup[4:1])) & _GEN_11)	// src/main/scala/MultiLayerSnnFlex.scala:215:31, :225:{18,35}, src/main/scala/chisel3/util/Mux.scala:30:73
              accum_1 <= {{8{io_sram_dout[15]}}, io_sram_dout[15:8]} + accum_1;	// src/main/scala/MultiLayerSnnFlex.scala:82:22, :223:32, :226:{32,45}
            if (neuronsInGroup > 5'h2 & _GEN_11)	// src/main/scala/MultiLayerSnnFlex.scala:215:31, :225:{18,35}, src/main/scala/chisel3/util/Mux.scala:30:73
              accum_2 <= {{8{io_sram_dout[23]}}, io_sram_dout[23:16]} + accum_2;	// src/main/scala/MultiLayerSnnFlex.scala:82:22, :223:32, :226:{32,45}
            if ((|(neuronsInGroup[4:2])) & _GEN_11)	// src/main/scala/MultiLayerSnnFlex.scala:215:31, :225:{18,35}, src/main/scala/chisel3/util/Mux.scala:30:73
              accum_3 <= {{8{io_sram_dout[31]}}, io_sram_dout[31:24]} + accum_3;	// src/main/scala/MultiLayerSnnFlex.scala:82:22, :223:32, :226:{32,45}
          end
          else begin	// src/main/scala/MultiLayerSnnFlex.scala:132:17
            if (_GEN_6 | ~_GEN_7 | _GEN_10) begin	// src/main/scala/MultiLayerSnnFlex.scala:73:30, :74:30, :79:29, :82:22, :132:17, :267:43, :269:49, :270:24
            end
            else begin	// src/main/scala/MultiLayerSnnFlex.scala:82:22, :132:17
              inputIdx <= 4'h0;	// src/main/scala/MultiLayerSnnFlex.scala:74:30
              accum_0 <= 16'h0;	// src/main/scala/MultiLayerSnnFlex.scala:82:{22,30}
              accum_1 <= 16'h0;	// src/main/scala/MultiLayerSnnFlex.scala:82:{22,30}
              accum_2 <= 16'h0;	// src/main/scala/MultiLayerSnnFlex.scala:82:{22,30}
              accum_3 <= 16'h0;	// src/main/scala/MultiLayerSnnFlex.scala:82:{22,30}
            end
            if (_GEN_6)	// src/main/scala/MultiLayerSnnFlex.scala:132:17
              layerSpikes <= layerSpikes | _layerSpikes_T_1[7:0];	// src/main/scala/MultiLayerSnnFlex.scala:85:28, :259:{34,42}
            else if (~_GEN_16 | _GEN_9) begin	// src/main/scala/MultiLayerSnnFlex.scala:78:29, :85:28, :132:17, :267:43, :269:{23,49}
            end
            else	// src/main/scala/MultiLayerSnnFlex.scala:85:28, :132:17, :267:43, :269:49
              layerSpikes <= 8'h0;	// src/main/scala/MultiLayerSnnFlex.scala:78:29, :85:28
          end
        end
        if (_GEN_15 | ~_GEN_16 | _GEN_9) begin	// src/main/scala/MultiLayerSnnFlex.scala:78:29, :79:29, :132:17, :267:43, :269:{23,49}
        end
        else	// src/main/scala/MultiLayerSnnFlex.scala:78:29, :132:17
          spikesBuf <= layerSpikes;	// src/main/scala/MultiLayerSnnFlex.scala:78:29, :85:28
        if (_GEN_15 | ~(_GEN_7 & _GEN_10)) begin	// src/main/scala/MultiLayerSnnFlex.scala:79:29, :132:17, :267:43, :269:49, :270:24
        end
        else	// src/main/scala/MultiLayerSnnFlex.scala:79:29, :132:17
          spikesOutReg <= layerSpikes[3:0];	// src/main/scala/MultiLayerSnnFlex.scala:79:29, :85:28, :270:38
        if (_GEN_0 & _GEN_1) begin	// src/main/scala/MultiLayerSnnFlex.scala:88:31, :132:17, :154:{26,35}, :158:24
          runtimeNLayers <= io_sram_dout[1:0];	// src/main/scala/MultiLayerSnnFlex.scala:88:31, :155:41
          firstWeightBase <= _headerBase_T_1;	// src/main/scala/MultiLayerSnnFlex.scala:95:32, :157:{40,56}
        end
        if (~_GEN_0 | _GEN_1) begin	// src/main/scala/MultiLayerSnnFlex.scala:89:34, :94:34, :132:17, :154:{26,35}
        end
        else	// src/main/scala/MultiLayerSnnFlex.scala:94:34, :132:17, :154:35
          previousLayerSize <= io_sram_dout[3:0];	// src/main/scala/MultiLayerSnnFlex.scala:94:34, :165:36
      end
      if (_GEN | ~_GEN_0 | _GEN_1 | (|_sizeEntryIdx_T)) begin	// src/main/scala/MultiLayerSnnFlex.scala:89:34, :132:17, :154:{26,35}, :166:42, :168:29
      end
      else	// src/main/scala/MultiLayerSnnFlex.scala:89:34, :132:17
        runtimeLayerSizes_0 <= io_sram_dout[3:0];	// src/main/scala/MultiLayerSnnFlex.scala:89:34, :165:36
      if (_GEN | ~_GEN_0 | _GEN_1 | _sizeEntryIdx_T != 2'h1) begin	// src/main/scala/MultiLayerSnnFlex.scala:89:34, :132:17, :154:{26,35}, :166:42, :168:29, :190:69
      end
      else	// src/main/scala/MultiLayerSnnFlex.scala:89:34, :132:17
        runtimeLayerSizes_1 <= io_sram_dout[3:0];	// src/main/scala/MultiLayerSnnFlex.scala:89:34, :165:36
      if (_GEN | ~_GEN_0 | _GEN_1 | _sizeEntryIdx_T != 2'h2) begin	// src/main/scala/MultiLayerSnnFlex.scala:89:34, :100:63, :132:17, :154:{26,35}, :166:42, :168:29
      end
      else	// src/main/scala/MultiLayerSnnFlex.scala:89:34, :132:17
        runtimeLayerSizes_2 <= io_sram_dout[3:0];	// src/main/scala/MultiLayerSnnFlex.scala:89:34, :165:36
      if (_GEN_19) begin	// src/main/scala/MultiLayerSnnFlex.scala:90:35, :132:17
      end
      else	// src/main/scala/MultiLayerSnnFlex.scala:90:35, :132:17
        runtimeLayerInputs_0 <= previousLayerSize;	// src/main/scala/MultiLayerSnnFlex.scala:90:35, :94:34
      if (_GEN_20) begin	// src/main/scala/MultiLayerSnnFlex.scala:90:35, :132:17
      end
      else	// src/main/scala/MultiLayerSnnFlex.scala:90:35, :132:17
        runtimeLayerInputs_1 <= previousLayerSize;	// src/main/scala/MultiLayerSnnFlex.scala:90:35, :94:34
      if (_GEN_19) begin	// src/main/scala/MultiLayerSnnFlex.scala:90:35, :91:36, :132:17
      end
      else	// src/main/scala/MultiLayerSnnFlex.scala:91:36, :132:17
        runtimeLayerOutputs_0 <= io_sram_dout[3:0];	// src/main/scala/MultiLayerSnnFlex.scala:91:36, :165:36
      if (_GEN_20) begin	// src/main/scala/MultiLayerSnnFlex.scala:90:35, :91:36, :132:17
      end
      else	// src/main/scala/MultiLayerSnnFlex.scala:91:36, :132:17
        runtimeLayerOutputs_1 <= io_sram_dout[3:0];	// src/main/scala/MultiLayerSnnFlex.scala:91:36, :165:36
      if (_GEN_19) begin	// src/main/scala/MultiLayerSnnFlex.scala:90:35, :92:35, :132:17
      end
      else	// src/main/scala/MultiLayerSnnFlex.scala:92:35, :132:17
        runtimeLayerGroups_0 <= _groups_T[3:2];	// src/main/scala/MultiLayerSnnFlex.scala:92:35, :175:{35,42}
      if (_GEN_20) begin	// src/main/scala/MultiLayerSnnFlex.scala:90:35, :92:35, :132:17
      end
      else	// src/main/scala/MultiLayerSnnFlex.scala:92:35, :132:17
        runtimeLayerGroups_1 <= _groups_T[3:2];	// src/main/scala/MultiLayerSnnFlex.scala:92:35, :175:{35,42}
      if (_GEN_19) begin	// src/main/scala/MultiLayerSnnFlex.scala:90:35, :93:34, :132:17
      end
      else	// src/main/scala/MultiLayerSnnFlex.scala:93:34, :132:17
        runtimeLayerBases_0 <= nextWeightBase;	// src/main/scala/MultiLayerSnnFlex.scala:93:34, :96:31
      if (_GEN_20) begin	// src/main/scala/MultiLayerSnnFlex.scala:90:35, :93:34, :132:17
      end
      else	// src/main/scala/MultiLayerSnnFlex.scala:93:34, :132:17
        runtimeLayerBases_1 <= nextWeightBase;	// src/main/scala/MultiLayerSnnFlex.scala:93:34, :96:31
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/MultiLayerSnnFlex.scala:26:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/MultiLayerSnnFlex.scala:26:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/MultiLayerSnnFlex.scala:26:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:5];	// src/main/scala/MultiLayerSnnFlex.scala:26:7
    initial begin	// src/main/scala/MultiLayerSnnFlex.scala:26:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/MultiLayerSnnFlex.scala:26:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/MultiLayerSnnFlex.scala:26:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/MultiLayerSnnFlex.scala:26:7
        for (logic [2:0] i = 3'h0; i < 3'h6; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/MultiLayerSnnFlex.scala:26:7
        end	// src/main/scala/MultiLayerSnnFlex.scala:26:7
        state = _RANDOM[3'h0][2:0];	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :71:30
        layerIdx = _RANDOM[3'h0][3];	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :71:30, :72:30
        groupIdx = _RANDOM[3'h0][5:4];	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :71:30, :73:30
        inputIdx = _RANDOM[3'h0][9:6];	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :71:30, :74:30
        configReadIdx = _RANDOM[3'h0][11:10];	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :71:30, :75:30
        spikesBuf = _RANDOM[3'h0][19:12];	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :71:30, :78:29
        spikesOutReg = _RANDOM[3'h0][23:20];	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :71:30, :79:29
        accum_0 = {_RANDOM[3'h0][31:24], _RANDOM[3'h1][7:0]};	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :71:30, :82:22
        accum_1 = _RANDOM[3'h1][23:8];	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :82:22
        accum_2 = {_RANDOM[3'h1][31:24], _RANDOM[3'h2][7:0]};	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :82:22
        accum_3 = _RANDOM[3'h2][23:8];	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :82:22
        layerSpikes = _RANDOM[3'h2][31:24];	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :82:22, :85:28
        runtimeNLayers = _RANDOM[3'h3][1:0];	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :88:31
        runtimeLayerSizes_0 = _RANDOM[3'h3][5:2];	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :88:31, :89:34
        runtimeLayerSizes_1 = _RANDOM[3'h3][9:6];	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :88:31, :89:34
        runtimeLayerSizes_2 = _RANDOM[3'h3][13:10];	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :88:31, :89:34
        runtimeLayerInputs_0 = _RANDOM[3'h3][17:14];	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :88:31, :90:35
        runtimeLayerInputs_1 = _RANDOM[3'h3][21:18];	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :88:31, :90:35
        runtimeLayerOutputs_0 = _RANDOM[3'h3][25:22];	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :88:31, :91:36
        runtimeLayerOutputs_1 = _RANDOM[3'h3][29:26];	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :88:31, :91:36
        runtimeLayerGroups_0 = _RANDOM[3'h3][31:30];	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :88:31, :92:35
        runtimeLayerGroups_1 = _RANDOM[3'h4][1:0];	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :92:35
        runtimeLayerBases_0 = _RANDOM[3'h4][9:2];	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :92:35, :93:34
        runtimeLayerBases_1 = _RANDOM[3'h4][17:10];	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :92:35, :93:34
        previousLayerSize = _RANDOM[3'h4][21:18];	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :92:35, :94:34
        firstWeightBase = _RANDOM[3'h4][29:22];	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :92:35, :95:32
        nextWeightBase = {_RANDOM[3'h4][31:30], _RANDOM[3'h5][5:0]};	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :92:35, :96:31
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/MultiLayerSnnFlex.scala:26:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/MultiLayerSnnFlex.scala:26:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_spikesOut = spikesOutReg;	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :79:29
  assign io_configNLayers = runtimeNLayers;	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :88:31
  assign io_configNInputs = runtimeLayerSizes_0;	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :89:34
  assign io_configNOutputs =
    (runtimeNLayers == 2'h0 ? runtimeLayerSizes_0 : 4'h0)
    | (runtimeNLayers == 2'h1 ? runtimeLayerSizes_1 : 4'h0)
    | (runtimeNLayers == 2'h2 ? runtimeLayerSizes_2 : 4'h0);	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :73:30, :74:30, :88:31, :89:34, :100:63, :190:69, src/main/scala/chisel3/util/Mux.scala:30:73
  assign io_busy = |state;	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :71:30, :125:20
  assign io_done = ~(_GEN | _GEN_0 | _GEN_4 | _GEN_6 | _GEN_7) & state == 3'h5;	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :71:30, :126:11, :132:17
  assign io_sram_csb =
    _GEN ? ~io_start : ~_GEN_0 & (_GEN_4 ? _GEN_5 : _GEN_6 | ~_GEN_7 | _GEN_8 & _GEN_9);	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :72:30, :73:30, :89:34, :121:16, :132:17, :134:22, :148:22, :154:35, :230:{21,39}, :267:{21,43}, :269:{23,49}, :291:22
  assign io_sram_addr =
    _GEN
      ? 8'h0
      : _GEN_0
          ? (_GEN_1 ? 8'h1 : _GEN_2 ? firstWeightBase : {6'h0, _nextConfigIdx_T})
          : _GEN_4
              ? (_GEN_5
                   ? 8'h0
                   : ((layerIdx ? 8'h0 : runtimeLayerBases_0)
                      | (layerIdx ? runtimeLayerBases_1 : 8'h0))
                     + {2'h0,
                        {2'h0, _nextInput_T}
                          * {4'h0,
                             (layerIdx ? 2'h0 : runtimeLayerGroups_0)
                               | (layerIdx ? runtimeLayerGroups_1 : 2'h0)}}
                     + {6'h0, groupIdx})
              : _GEN_6 | ~_GEN_7
                  ? 8'h0
                  : _GEN_8
                      ? (_GEN_9
                           ? 8'h0
                           : (_nextLayer_T ? 8'h0 : runtimeLayerBases_0)
                             | (_nextLayer_T ? runtimeLayerBases_1 : 8'h0))
                      : ((layerIdx ? 8'h0 : runtimeLayerBases_0)
                         | (layerIdx ? runtimeLayerBases_1 : 8'h0))
                        + {6'h0, _nextGroup_T};	// src/main/scala/MultiLayerSnnFlex.scala:26:7, :72:30, :73:30, :74:30, :78:29, :92:35, :93:34, :95:32, :116:{42,50,90}, :123:16, :132:17, :134:22, :154:{26,35}, :163:24, :192:{28,47}, :200:24, :202:45, :205:24, :230:{21,39}, :233:34, :235:22, :267:{21,43}, :269:{23,49}, :274:36, :282:24, :286:34, :292:22, src/main/scala/chisel3/util/Mux.scala:30:73
endmodule

module WishboneMultiLayerSnnFlexTop(	// src/main/scala/GenerateSnn.scala:17:12
  input         clock,	// src/main/scala/GenerateSnn.scala:17:12
                reset,	// src/main/scala/GenerateSnn.scala:17:12
                wb_cyc,	// src/main/scala/WishboneMultiLayerSnnFlex.scala:10:14
                wb_stb,	// src/main/scala/WishboneMultiLayerSnnFlex.scala:10:14
                wb_we,	// src/main/scala/WishboneMultiLayerSnnFlex.scala:10:14
  input  [31:0] wb_addr,	// src/main/scala/WishboneMultiLayerSnnFlex.scala:10:14
                wb_din,	// src/main/scala/WishboneMultiLayerSnnFlex.scala:10:14
  output [31:0] wb_dout,	// src/main/scala/WishboneMultiLayerSnnFlex.scala:10:14
  input  [3:0]  wb_sel,	// src/main/scala/WishboneMultiLayerSnnFlex.scala:10:14
  output        wb_ack,	// src/main/scala/WishboneMultiLayerSnnFlex.scala:10:14
  output [3:0]  io_spikesOut	// src/main/scala/WishboneMultiLayerSnnFlex.scala:11:14
);

  wire [3:0]  _core_io_spikesOut;	// src/main/scala/WishboneMultiLayerSnnFlex.scala:18:28
  wire [1:0]  _core_io_configNLayers;	// src/main/scala/WishboneMultiLayerSnnFlex.scala:18:28
  wire [3:0]  _core_io_configNInputs;	// src/main/scala/WishboneMultiLayerSnnFlex.scala:18:28
  wire [3:0]  _core_io_configNOutputs;	// src/main/scala/WishboneMultiLayerSnnFlex.scala:18:28
  wire        _core_io_busy;	// src/main/scala/WishboneMultiLayerSnnFlex.scala:18:28
  wire        _core_io_done;	// src/main/scala/WishboneMultiLayerSnnFlex.scala:18:28
  wire        _core_io_sram_csb;	// src/main/scala/WishboneMultiLayerSnnFlex.scala:18:28
  wire [7:0]  _core_io_sram_addr;	// src/main/scala/WishboneMultiLayerSnnFlex.scala:18:28
  wire        _shell_core_start;	// src/main/scala/WishboneMultiLayerSnnFlex.scala:15:29
  wire [7:0]  _shell_core_spikesIn;	// src/main/scala/WishboneMultiLayerSnnFlex.scala:15:29
  wire [31:0] _shell_core_sram_dout;	// src/main/scala/WishboneMultiLayerSnnFlex.scala:15:29
  WishboneMultiLayerSnnShell shell (	// src/main/scala/WishboneMultiLayerSnnFlex.scala:15:29
    .clock               (clock),
    .reset               (reset),
    .wb_cyc              (wb_cyc),
    .wb_stb              (wb_stb),
    .wb_we               (wb_we),
    .wb_addr             (wb_addr),
    .wb_din              (wb_din),
    .wb_dout             (wb_dout),
    .wb_sel              (wb_sel),
    .wb_ack              (wb_ack),
    .io_spikesOut        (io_spikesOut),
    .core_start          (_shell_core_start),
    .core_spikesIn       (_shell_core_spikesIn),
    .core_busy           (_core_io_busy),	// src/main/scala/WishboneMultiLayerSnnFlex.scala:18:28
    .core_done           (_core_io_done),	// src/main/scala/WishboneMultiLayerSnnFlex.scala:18:28
    .core_spikesOut      (_core_io_spikesOut),	// src/main/scala/WishboneMultiLayerSnnFlex.scala:18:28
    .core_configNLayers  (_core_io_configNLayers),	// src/main/scala/WishboneMultiLayerSnnFlex.scala:18:28
    .core_configNInputs  (_core_io_configNInputs),	// src/main/scala/WishboneMultiLayerSnnFlex.scala:18:28
    .core_configNOutputs (_core_io_configNOutputs),	// src/main/scala/WishboneMultiLayerSnnFlex.scala:18:28
    .core_sram_csb       (_core_io_sram_csb),	// src/main/scala/WishboneMultiLayerSnnFlex.scala:18:28
    .core_sram_addr      (_core_io_sram_addr),	// src/main/scala/WishboneMultiLayerSnnFlex.scala:18:28
    .core_sram_dout      (_shell_core_sram_dout)
  );
  MultiLayerSnnFlex core (	// src/main/scala/WishboneMultiLayerSnnFlex.scala:18:28
    .clock             (clock),
    .reset             (reset),
    .io_spikesIn       (_shell_core_spikesIn),	// src/main/scala/WishboneMultiLayerSnnFlex.scala:15:29
    .io_spikesOut      (_core_io_spikesOut),
    .io_configNLayers  (_core_io_configNLayers),
    .io_configNInputs  (_core_io_configNInputs),
    .io_configNOutputs (_core_io_configNOutputs),
    .io_start          (_shell_core_start),	// src/main/scala/WishboneMultiLayerSnnFlex.scala:15:29
    .io_busy           (_core_io_busy),
    .io_done           (_core_io_done),
    .io_sram_csb       (_core_io_sram_csb),
    .io_sram_addr      (_core_io_sram_addr),
    .io_sram_dout      (_shell_core_sram_dout)	// src/main/scala/WishboneMultiLayerSnnFlex.scala:15:29
  );
endmodule
