// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module LIFNeuron(	// src/main/scala/LIFNeuron.scala:10:7
  input         clock,	// src/main/scala/LIFNeuron.scala:10:7
                reset,	// src/main/scala/LIFNeuron.scala:10:7
  input  [15:0] io_in,	// src/main/scala/LIFNeuron.scala:11:14
  output        io_spike	// src/main/scala/LIFNeuron.scala:11:14
);

  reg  [15:0] potential;	// src/main/scala/LIFNeuron.scala:16:26
  wire [15:0] _updated_T_3 = potential + io_in - 16'h1;	// src/main/scala/LIFNeuron.scala:16:26, :18:35
  wire        io_spike_0 = $signed(_updated_T_3) > 16'sh3F;	// src/main/scala/LIFNeuron.scala:18:35, :20:16
  always @(posedge clock) begin	// src/main/scala/LIFNeuron.scala:10:7
    if (reset)	// src/main/scala/LIFNeuron.scala:10:7
      potential <= 16'h0;	// src/main/scala/LIFNeuron.scala:16:26
    else if (io_spike_0 | $signed(_updated_T_3) < 16'sh0)	// src/main/scala/LIFNeuron.scala:16:26, :18:35, :20:{16,32}, :21:15, :23:{22,29}, :24:15, :27:15
      potential <= 16'h0;	// src/main/scala/LIFNeuron.scala:16:26
    else	// src/main/scala/LIFNeuron.scala:20:32, :21:15, :23:29, :24:15, :27:15
      potential <= _updated_T_3;	// src/main/scala/LIFNeuron.scala:16:26, :18:35
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/LIFNeuron.scala:10:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/LIFNeuron.scala:10:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/LIFNeuron.scala:10:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// src/main/scala/LIFNeuron.scala:10:7
    initial begin	// src/main/scala/LIFNeuron.scala:10:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/LIFNeuron.scala:10:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/LIFNeuron.scala:10:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/LIFNeuron.scala:10:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/LIFNeuron.scala:10:7
        potential = _RANDOM[/*Zero width*/ 1'b0][15:0];	// src/main/scala/LIFNeuron.scala:10:7, :16:26
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/LIFNeuron.scala:10:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/LIFNeuron.scala:10:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_spike = io_spike_0;	// src/main/scala/LIFNeuron.scala:10:7, :20:16
endmodule

module SnnLayerSram(	// src/main/scala/SnnLayerSram.scala:18:7
  input         clock,	// src/main/scala/SnnLayerSram.scala:18:7
                reset,	// src/main/scala/SnnLayerSram.scala:18:7
                io_spikesIn_0,	// src/main/scala/SnnLayerSram.scala:29:14
                io_spikesIn_1,	// src/main/scala/SnnLayerSram.scala:29:14
                io_spikesIn_2,	// src/main/scala/SnnLayerSram.scala:29:14
                io_spikesIn_3,	// src/main/scala/SnnLayerSram.scala:29:14
                io_spikesIn_4,	// src/main/scala/SnnLayerSram.scala:29:14
                io_spikesIn_5,	// src/main/scala/SnnLayerSram.scala:29:14
                io_spikesIn_6,	// src/main/scala/SnnLayerSram.scala:29:14
                io_spikesIn_7,	// src/main/scala/SnnLayerSram.scala:29:14
  output        io_spikesOut_0,	// src/main/scala/SnnLayerSram.scala:29:14
                io_spikesOut_1,	// src/main/scala/SnnLayerSram.scala:29:14
                io_spikesOut_2,	// src/main/scala/SnnLayerSram.scala:29:14
                io_spikesOut_3,	// src/main/scala/SnnLayerSram.scala:29:14
  input         io_start,	// src/main/scala/SnnLayerSram.scala:29:14
  output        io_busy,	// src/main/scala/SnnLayerSram.scala:29:14
                io_done,	// src/main/scala/SnnLayerSram.scala:29:14
                io_sram_csb,	// src/main/scala/SnnLayerSram.scala:29:14
  output [2:0]  io_sram_addr,	// src/main/scala/SnnLayerSram.scala:29:14
  input  [31:0] io_sram_dout	// src/main/scala/SnnLayerSram.scala:29:14
);

  reg  [1:0]  state;	// src/main/scala/SnnLayerSram.scala:41:24
  reg  [2:0]  cntReg;	// src/main/scala/SnnLayerSram.scala:42:24
  reg         spikesReg_0;	// src/main/scala/SnnLayerSram.scala:45:26
  reg         spikesReg_1;	// src/main/scala/SnnLayerSram.scala:45:26
  reg         spikesReg_2;	// src/main/scala/SnnLayerSram.scala:45:26
  reg         spikesReg_3;	// src/main/scala/SnnLayerSram.scala:45:26
  reg         spikesReg_4;	// src/main/scala/SnnLayerSram.scala:45:26
  reg         spikesReg_5;	// src/main/scala/SnnLayerSram.scala:45:26
  reg         spikesReg_6;	// src/main/scala/SnnLayerSram.scala:45:26
  reg         spikesReg_7;	// src/main/scala/SnnLayerSram.scala:45:26
  reg  [15:0] accum_0;	// src/main/scala/SnnLayerSram.scala:48:22
  reg  [15:0] accum_1;	// src/main/scala/SnnLayerSram.scala:48:22
  reg  [15:0] accum_2;	// src/main/scala/SnnLayerSram.scala:48:22
  reg  [15:0] accum_3;	// src/main/scala/SnnLayerSram.scala:48:22
  wire        _GEN = state == 2'h0;	// src/main/scala/SnnLayerSram.scala:18:7, :41:24, :68:17
  wire        _GEN_0 = state == 2'h1;	// src/main/scala/SnnLayerSram.scala:18:7, :41:24, :68:17
  reg         casez_tmp;	// src/main/scala/SnnLayerSram.scala:90:34
  always_comb begin	// src/main/scala/SnnLayerSram.scala:90:34
    casez (cntReg)	// src/main/scala/SnnLayerSram.scala:42:24, :90:34
      3'b000:
        casez_tmp = spikesReg_0;	// src/main/scala/SnnLayerSram.scala:45:26, :90:34
      3'b001:
        casez_tmp = spikesReg_1;	// src/main/scala/SnnLayerSram.scala:45:26, :90:34
      3'b010:
        casez_tmp = spikesReg_2;	// src/main/scala/SnnLayerSram.scala:45:26, :90:34
      3'b011:
        casez_tmp = spikesReg_3;	// src/main/scala/SnnLayerSram.scala:45:26, :90:34
      3'b100:
        casez_tmp = spikesReg_4;	// src/main/scala/SnnLayerSram.scala:45:26, :90:34
      3'b101:
        casez_tmp = spikesReg_5;	// src/main/scala/SnnLayerSram.scala:45:26, :90:34
      3'b110:
        casez_tmp = spikesReg_6;	// src/main/scala/SnnLayerSram.scala:45:26, :90:34
      default:
        casez_tmp = spikesReg_7;	// src/main/scala/SnnLayerSram.scala:45:26, :90:34
    endcase	// src/main/scala/SnnLayerSram.scala:42:24, :90:34
  end // always_comb
  wire        _GEN_1 = ~_GEN_0 | (&cntReg);	// src/main/scala/SnnLayerSram.scala:42:24, :55:16, :68:17, :95:{19,36}
  wire [2:0]  _cntReg_T = cntReg + 3'h1;	// src/main/scala/SnnLayerSram.scala:42:24, :101:32
  wire        _GEN_2 = state == 2'h2;	// src/main/scala/SnnLayerSram.scala:18:7, :41:24, :68:17
  wire        _GEN_3 = _GEN | _GEN_0;	// src/main/scala/SnnLayerSram.scala:64:22, :68:17
  wire        _GEN_4 = _GEN_3 | ~_GEN_2;	// src/main/scala/SnnLayerSram.scala:64:22, :68:17
  reg  [1:0]  casez_tmp_0;	// src/main/scala/SnnLayerSram.scala:68:17, :70:22
  always_comb begin	// src/main/scala/SnnLayerSram.scala:41:24, :68:17, :70:22, :95:36, :112:15
    casez (state)	// src/main/scala/SnnLayerSram.scala:41:24, :68:17, :70:22, :95:36, :112:15
      2'b00:
        casez_tmp_0 = io_start ? 2'h1 : state;	// src/main/scala/SnnLayerSram.scala:18:7, :41:24, :68:17, :70:22, :74:16, :95:36, :112:15
      2'b01:
        casez_tmp_0 = (&cntReg) ? 2'h2 : state;	// src/main/scala/SnnLayerSram.scala:18:7, :41:24, :42:24, :68:17, :70:22, :95:{19,36}, :97:15, :112:15
      2'b10:
        casez_tmp_0 = 2'h0;	// src/main/scala/SnnLayerSram.scala:18:7, :41:24, :68:17, :70:22, :95:36, :112:15
      default:
        casez_tmp_0 = state;	// src/main/scala/SnnLayerSram.scala:41:24, :68:17, :70:22, :95:36, :112:15
    endcase	// src/main/scala/SnnLayerSram.scala:41:24, :68:17, :70:22, :95:36, :112:15
  end // always_comb
  always @(posedge clock) begin	// src/main/scala/SnnLayerSram.scala:18:7
    if (reset) begin	// src/main/scala/SnnLayerSram.scala:18:7
      state <= 2'h0;	// src/main/scala/SnnLayerSram.scala:18:7, :41:24
      cntReg <= 3'h0;	// src/main/scala/SnnLayerSram.scala:42:24
      spikesReg_0 <= 1'h0;	// src/main/scala/SnnLayerSram.scala:45:{26,34}
      spikesReg_1 <= 1'h0;	// src/main/scala/SnnLayerSram.scala:45:{26,34}
      spikesReg_2 <= 1'h0;	// src/main/scala/SnnLayerSram.scala:45:{26,34}
      spikesReg_3 <= 1'h0;	// src/main/scala/SnnLayerSram.scala:45:{26,34}
      spikesReg_4 <= 1'h0;	// src/main/scala/SnnLayerSram.scala:45:{26,34}
      spikesReg_5 <= 1'h0;	// src/main/scala/SnnLayerSram.scala:45:{26,34}
      spikesReg_6 <= 1'h0;	// src/main/scala/SnnLayerSram.scala:45:{26,34}
      spikesReg_7 <= 1'h0;	// src/main/scala/SnnLayerSram.scala:45:{26,34}
      accum_0 <= 16'h0;	// src/main/scala/SnnLayerSram.scala:48:{22,30}
      accum_1 <= 16'h0;	// src/main/scala/SnnLayerSram.scala:48:{22,30}
      accum_2 <= 16'h0;	// src/main/scala/SnnLayerSram.scala:48:{22,30}
      accum_3 <= 16'h0;	// src/main/scala/SnnLayerSram.scala:48:{22,30}
    end
    else begin	// src/main/scala/SnnLayerSram.scala:18:7
      state <= casez_tmp_0;	// src/main/scala/SnnLayerSram.scala:41:24, :68:17, :70:22
      if (_GEN) begin	// src/main/scala/SnnLayerSram.scala:68:17
        if (io_start) begin	// src/main/scala/SnnLayerSram.scala:29:14
          cntReg <= 3'h0;	// src/main/scala/SnnLayerSram.scala:42:24
          accum_0 <= 16'h0;	// src/main/scala/SnnLayerSram.scala:48:{22,30}
          accum_1 <= 16'h0;	// src/main/scala/SnnLayerSram.scala:48:{22,30}
          accum_2 <= 16'h0;	// src/main/scala/SnnLayerSram.scala:48:{22,30}
          accum_3 <= 16'h0;	// src/main/scala/SnnLayerSram.scala:48:{22,30}
        end
      end
      else begin	// src/main/scala/SnnLayerSram.scala:68:17
        if (_GEN_1) begin	// src/main/scala/SnnLayerSram.scala:42:24, :55:16, :68:17, :95:36
        end
        else	// src/main/scala/SnnLayerSram.scala:42:24, :68:17, :95:36
          cntReg <= _cntReg_T;	// src/main/scala/SnnLayerSram.scala:42:24, :101:32
        if (_GEN_0 & casez_tmp) begin	// src/main/scala/SnnLayerSram.scala:48:22, :68:17, :90:34, :91:20
          accum_0 <= {{8{io_sram_dout[7]}}, io_sram_dout[7:0]} + accum_0;	// src/main/scala/SnnLayerSram.scala:48:22, :88:32, :91:{32,45}
          accum_1 <= {{8{io_sram_dout[15]}}, io_sram_dout[15:8]} + accum_1;	// src/main/scala/SnnLayerSram.scala:48:22, :88:32, :91:{32,45}
          accum_2 <= {{8{io_sram_dout[23]}}, io_sram_dout[23:16]} + accum_2;	// src/main/scala/SnnLayerSram.scala:48:22, :88:32, :91:{32,45}
          accum_3 <= {{8{io_sram_dout[31]}}, io_sram_dout[31:24]} + accum_3;	// src/main/scala/SnnLayerSram.scala:48:22, :88:32, :91:{32,45}
        end
      end
      if (_GEN & io_start) begin	// src/main/scala/SnnLayerSram.scala:45:26, :68:17, :70:22, :71:19
        spikesReg_0 <= io_spikesIn_0;	// src/main/scala/SnnLayerSram.scala:45:26
        spikesReg_1 <= io_spikesIn_1;	// src/main/scala/SnnLayerSram.scala:45:26
        spikesReg_2 <= io_spikesIn_2;	// src/main/scala/SnnLayerSram.scala:45:26
        spikesReg_3 <= io_spikesIn_3;	// src/main/scala/SnnLayerSram.scala:45:26
        spikesReg_4 <= io_spikesIn_4;	// src/main/scala/SnnLayerSram.scala:45:26
        spikesReg_5 <= io_spikesIn_5;	// src/main/scala/SnnLayerSram.scala:45:26
        spikesReg_6 <= io_spikesIn_6;	// src/main/scala/SnnLayerSram.scala:45:26
        spikesReg_7 <= io_spikesIn_7;	// src/main/scala/SnnLayerSram.scala:45:26
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/SnnLayerSram.scala:18:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/SnnLayerSram.scala:18:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/SnnLayerSram.scala:18:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:2];	// src/main/scala/SnnLayerSram.scala:18:7
    initial begin	// src/main/scala/SnnLayerSram.scala:18:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/SnnLayerSram.scala:18:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/SnnLayerSram.scala:18:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/SnnLayerSram.scala:18:7
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/SnnLayerSram.scala:18:7
        end	// src/main/scala/SnnLayerSram.scala:18:7
        state = _RANDOM[2'h0][1:0];	// src/main/scala/SnnLayerSram.scala:18:7, :41:24
        cntReg = _RANDOM[2'h0][4:2];	// src/main/scala/SnnLayerSram.scala:18:7, :41:24, :42:24
        spikesReg_0 = _RANDOM[2'h0][5];	// src/main/scala/SnnLayerSram.scala:18:7, :41:24, :45:26
        spikesReg_1 = _RANDOM[2'h0][6];	// src/main/scala/SnnLayerSram.scala:18:7, :41:24, :45:26
        spikesReg_2 = _RANDOM[2'h0][7];	// src/main/scala/SnnLayerSram.scala:18:7, :41:24, :45:26
        spikesReg_3 = _RANDOM[2'h0][8];	// src/main/scala/SnnLayerSram.scala:18:7, :41:24, :45:26
        spikesReg_4 = _RANDOM[2'h0][9];	// src/main/scala/SnnLayerSram.scala:18:7, :41:24, :45:26
        spikesReg_5 = _RANDOM[2'h0][10];	// src/main/scala/SnnLayerSram.scala:18:7, :41:24, :45:26
        spikesReg_6 = _RANDOM[2'h0][11];	// src/main/scala/SnnLayerSram.scala:18:7, :41:24, :45:26
        spikesReg_7 = _RANDOM[2'h0][12];	// src/main/scala/SnnLayerSram.scala:18:7, :41:24, :45:26
        accum_0 = _RANDOM[2'h0][28:13];	// src/main/scala/SnnLayerSram.scala:18:7, :41:24, :48:22
        accum_1 = {_RANDOM[2'h0][31:29], _RANDOM[2'h1][12:0]};	// src/main/scala/SnnLayerSram.scala:18:7, :41:24, :48:22
        accum_2 = _RANDOM[2'h1][28:13];	// src/main/scala/SnnLayerSram.scala:18:7, :48:22
        accum_3 = {_RANDOM[2'h1][31:29], _RANDOM[2'h2][12:0]};	// src/main/scala/SnnLayerSram.scala:18:7, :48:22
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/SnnLayerSram.scala:18:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/SnnLayerSram.scala:18:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  LIFNeuron neurons_0 (	// src/main/scala/SnnLayerSram.scala:51:38
    .clock    (clock),
    .reset    (reset),
    .io_in    (_GEN_4 ? 16'h0 : accum_0),	// src/main/scala/SnnLayerSram.scala:48:{22,30}, :64:22, :68:17
    .io_spike (io_spikesOut_0)
  );
  LIFNeuron neurons_1 (	// src/main/scala/SnnLayerSram.scala:51:38
    .clock    (clock),
    .reset    (reset),
    .io_in    (_GEN_4 ? 16'h0 : accum_1),	// src/main/scala/SnnLayerSram.scala:48:{22,30}, :64:22, :68:17
    .io_spike (io_spikesOut_1)
  );
  LIFNeuron neurons_2 (	// src/main/scala/SnnLayerSram.scala:51:38
    .clock    (clock),
    .reset    (reset),
    .io_in    (_GEN_4 ? 16'h0 : accum_2),	// src/main/scala/SnnLayerSram.scala:48:{22,30}, :64:22, :68:17
    .io_spike (io_spikesOut_2)
  );
  LIFNeuron neurons_3 (	// src/main/scala/SnnLayerSram.scala:51:38
    .clock    (clock),
    .reset    (reset),
    .io_in    (_GEN_4 ? 16'h0 : accum_3),	// src/main/scala/SnnLayerSram.scala:48:{22,30}, :64:22, :68:17
    .io_spike (io_spikesOut_3)
  );
  assign io_busy = |state;	// src/main/scala/SnnLayerSram.scala:18:7, :41:24, :59:20
  assign io_done = ~_GEN_3 & _GEN_2;	// src/main/scala/SnnLayerSram.scala:18:7, :60:11, :64:22, :68:17
  assign io_sram_csb = _GEN ? ~io_start : _GEN_1;	// src/main/scala/SnnLayerSram.scala:18:7, :45:34, :55:16, :68:17, :70:22, :76:22, :95:36
  assign io_sram_addr = _GEN | ~_GEN_0 | (&cntReg) ? 3'h0 : _cntReg_T;	// src/main/scala/SnnLayerSram.scala:18:7, :42:24, :55:16, :68:17, :70:22, :95:{19,36}, :101:32
endmodule

// external module sky130_sram_1kbyte_1rw1r_32x256_8

module WishboneSnn(	// src/main/scala/WishboneSnn.scala:20:7
  input         clock,	// src/main/scala/WishboneSnn.scala:20:7
                reset,	// src/main/scala/WishboneSnn.scala:20:7
                wb_cyc,	// src/main/scala/WishboneSnn.scala:37:14
                wb_stb,	// src/main/scala/WishboneSnn.scala:37:14
                wb_we,	// src/main/scala/WishboneSnn.scala:37:14
  input  [31:0] wb_addr,	// src/main/scala/WishboneSnn.scala:37:14
                wb_din,	// src/main/scala/WishboneSnn.scala:37:14
  output [31:0] wb_dout,	// src/main/scala/WishboneSnn.scala:37:14
  input  [3:0]  wb_sel,	// src/main/scala/WishboneSnn.scala:37:14
  output        wb_ack,	// src/main/scala/WishboneSnn.scala:37:14
  output [3:0]  io_spikesOut	// src/main/scala/WishboneSnn.scala:38:14
);

  wire        startPulse;	// src/main/scala/WishboneSnn.scala:79:33, :117:17, :118:24
  wire [31:0] _ram_dout0;	// src/main/scala/WishboneSnn.scala:54:21
  wire        _snnLayer_io_spikesOut_0;	// src/main/scala/WishboneSnn.scala:43:24
  wire        _snnLayer_io_spikesOut_1;	// src/main/scala/WishboneSnn.scala:43:24
  wire        _snnLayer_io_spikesOut_2;	// src/main/scala/WishboneSnn.scala:43:24
  wire        _snnLayer_io_spikesOut_3;	// src/main/scala/WishboneSnn.scala:43:24
  wire        _snnLayer_io_busy;	// src/main/scala/WishboneSnn.scala:43:24
  wire        _snnLayer_io_done;	// src/main/scala/WishboneSnn.scala:43:24
  wire        _snnLayer_io_sram_csb;	// src/main/scala/WishboneSnn.scala:43:24
  wire [2:0]  _snnLayer_io_sram_addr;	// src/main/scala/WishboneSnn.scala:43:24
  reg  [7:0]  spikesInReg;	// src/main/scala/WishboneSnn.scala:77:29
  reg  [3:0]  spikesOutReg;	// src/main/scala/WishboneSnn.scala:78:29
  reg         doneFlag;	// src/main/scala/WishboneSnn.scala:80:29
  wire        snnActive = _snnLayer_io_busy | startPulse;	// src/main/scala/WishboneSnn.scala:43:24, :79:33, :85:39, :117:17, :118:24
  wire        wbActive = wb_cyc & wb_stb;	// src/main/scala/WishboneSnn.scala:92:29
  wire        wbWrite = wbActive & wb_we;	// src/main/scala/WishboneSnn.scala:92:29, :94:31
  wire        _GEN = wb_addr[3:2] == 2'h0;	// src/main/scala/WishboneSnn.scala:96:28, :108:22
  reg  [31:0] casez_tmp;	// src/main/scala/WishboneSnn.scala:108:22, :109:27
  always_comb begin	// src/main/scala/WishboneSnn.scala:101:11, :108:22, :109:27, :110:27, :111:27
    casez (wb_addr[3:2])	// src/main/scala/WishboneSnn.scala:96:28, :101:11, :108:22, :109:27, :110:27, :111:27
      2'b00:
        casez_tmp = {30'h0, doneFlag, _snnLayer_io_busy};	// src/main/scala/WishboneSnn.scala:43:24, :80:29, :101:11, :108:22, :109:27, :110:27, :111:27
      2'b01:
        casez_tmp = {24'h0, spikesInReg};	// src/main/scala/WishboneSnn.scala:77:29, :101:11, :108:22, :109:27, :110:27, :111:27
      2'b10:
        casez_tmp = {28'h0, spikesOutReg};	// src/main/scala/WishboneSnn.scala:78:29, :101:11, :108:22, :109:27, :110:27, :111:27
      default:
        casez_tmp = 32'h0;	// src/main/scala/WishboneSnn.scala:50:57, :101:11, :108:22, :109:27, :110:27, :111:27
    endcase	// src/main/scala/WishboneSnn.scala:96:28, :101:11, :108:22, :109:27, :110:27, :111:27
  end // always_comb
  assign startPulse = wbWrite & ~(|(wb_addr[31:4])) & _GEN & wb_din[0];	// src/main/scala/WishboneSnn.scala:79:33, :94:31, :97:29, :108:22, :117:17, :118:24, :121:22, :122:39
  wire        _GEN_0 = wbActive & (|(wb_addr[31:4]));	// src/main/scala/WishboneSnn.scala:92:29, :97:29, :134:23
  wire        _GEN_1 = snnActive | ~_GEN_0;	// src/main/scala/WishboneSnn.scala:47:45, :50:57, :85:39, :129:19, :134:{23,40}, :136:15
  always @(posedge clock) begin	// src/main/scala/WishboneSnn.scala:20:7
    if (reset) begin	// src/main/scala/WishboneSnn.scala:20:7
      spikesInReg <= 8'h0;	// src/main/scala/WishboneSnn.scala:77:29
      spikesOutReg <= 4'h0;	// src/main/scala/WishboneSnn.scala:78:29
      doneFlag <= 1'h0;	// src/main/scala/WishboneSnn.scala:20:7, :80:29
    end
    else begin	// src/main/scala/WishboneSnn.scala:20:7
      if (~wbWrite | (|(wb_addr[31:4])) | _GEN | wb_addr[3:2] != 2'h1) begin	// src/main/scala/WishboneSnn.scala:77:29, :94:31, :96:28, :97:29, :108:22, :117:17, :118:24
      end
      else	// src/main/scala/WishboneSnn.scala:77:29, :117:17, :118:24
        spikesInReg <= wb_din[7:0];	// src/main/scala/WishboneSnn.scala:77:29, :123:40
      if (_snnLayer_io_done)	// src/main/scala/WishboneSnn.scala:43:24
        spikesOutReg <=
          {_snnLayer_io_spikesOut_3,
           _snnLayer_io_spikesOut_2,
           _snnLayer_io_spikesOut_1,
           _snnLayer_io_spikesOut_0};	// src/main/scala/WishboneSnn.scala:43:24, :78:29, :147:43
      doneFlag <= ~startPulse & (_snnLayer_io_done | doneFlag);	// src/main/scala/WishboneSnn.scala:43:24, :79:33, :80:29, :117:17, :118:24, :146:26, :148:18, :150:20, :151:14
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/WishboneSnn.scala:20:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/WishboneSnn.scala:20:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/WishboneSnn.scala:20:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// src/main/scala/WishboneSnn.scala:20:7
    initial begin	// src/main/scala/WishboneSnn.scala:20:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/WishboneSnn.scala:20:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/WishboneSnn.scala:20:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/WishboneSnn.scala:20:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/WishboneSnn.scala:20:7
        spikesInReg = _RANDOM[/*Zero width*/ 1'b0][7:0];	// src/main/scala/WishboneSnn.scala:20:7, :77:29
        spikesOutReg = _RANDOM[/*Zero width*/ 1'b0][11:8];	// src/main/scala/WishboneSnn.scala:20:7, :77:29, :78:29
        doneFlag = _RANDOM[/*Zero width*/ 1'b0][12];	// src/main/scala/WishboneSnn.scala:20:7, :77:29, :80:29
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/WishboneSnn.scala:20:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/WishboneSnn.scala:20:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  SnnLayerSram snnLayer (	// src/main/scala/WishboneSnn.scala:43:24
    .clock          (clock),
    .reset          (reset),
    .io_spikesIn_0  (spikesInReg[0]),	// src/main/scala/WishboneSnn.scala:77:29, :143:69
    .io_spikesIn_1  (spikesInReg[1]),	// src/main/scala/WishboneSnn.scala:77:29, :143:69
    .io_spikesIn_2  (spikesInReg[2]),	// src/main/scala/WishboneSnn.scala:77:29, :143:69
    .io_spikesIn_3  (spikesInReg[3]),	// src/main/scala/WishboneSnn.scala:77:29, :143:69
    .io_spikesIn_4  (spikesInReg[4]),	// src/main/scala/WishboneSnn.scala:77:29, :143:69
    .io_spikesIn_5  (spikesInReg[5]),	// src/main/scala/WishboneSnn.scala:77:29, :143:69
    .io_spikesIn_6  (spikesInReg[6]),	// src/main/scala/WishboneSnn.scala:77:29, :143:69
    .io_spikesIn_7  (spikesInReg[7]),	// src/main/scala/WishboneSnn.scala:77:29, :143:69
    .io_spikesOut_0 (_snnLayer_io_spikesOut_0),
    .io_spikesOut_1 (_snnLayer_io_spikesOut_1),
    .io_spikesOut_2 (_snnLayer_io_spikesOut_2),
    .io_spikesOut_3 (_snnLayer_io_spikesOut_3),
    .io_start       (startPulse),	// src/main/scala/WishboneSnn.scala:79:33, :117:17, :118:24
    .io_busy        (_snnLayer_io_busy),
    .io_done        (_snnLayer_io_done),
    .io_sram_csb    (_snnLayer_io_sram_csb),
    .io_sram_addr   (_snnLayer_io_sram_addr),
    .io_sram_dout   (_ram_dout0)	// src/main/scala/WishboneSnn.scala:54:21
  );
  sky130_sram_1kbyte_1rw1r_32x256_8 ram (	// src/main/scala/WishboneSnn.scala:54:21
    .clk0   (clock),
    .csb0   (snnActive ? _snnLayer_io_sram_csb : ~_GEN_0),	// src/main/scala/WishboneSnn.scala:43:24, :46:45, :49:57, :85:39, :129:19, :130:14, :134:{23,40}, :135:15
    .web0   (snnActive | ~_GEN_0 | ~wb_we),	// src/main/scala/WishboneSnn.scala:46:45, :47:45, :49:57, :85:39, :129:19, :131:14, :134:{23,40}, :136:{15,21}
    .wmask0 (_GEN_1 ? 4'hF : wb_sel),	// src/main/scala/WishboneSnn.scala:48:46, :50:57, :129:19, :133:15, :134:40
    .addr0
      (snnActive ? {5'h0, _snnLayer_io_sram_addr} : _GEN_0 ? wb_addr[9:2] - 8'h4 : 8'h0),	// src/main/scala/WishboneSnn.scala:43:24, :49:57, :77:29, :85:39, :98:{28,35}, :129:19, :132:{14,33}, :134:{23,40}, :137:15
    .din0   (_GEN_1 ? 32'h0 : wb_din),	// src/main/scala/WishboneSnn.scala:50:57, :129:19, :134:40
    .dout0  (_ram_dout0),
    .clk1   (clock),
    .csb1   (1'h1),	// src/main/scala/WishboneSnn.scala:20:7
    .addr1  (8'h0),	// src/main/scala/WishboneSnn.scala:77:29
    .dout1  (/* unused */)
  );
  assign wb_dout =
    wbActive & ~wb_we ? ((|(wb_addr[31:4])) ? _ram_dout0 : casez_tmp) : 32'h0;	// src/main/scala/WishboneSnn.scala:20:7, :50:57, :54:21, :92:29, :95:{31,34}, :97:29, :101:11, :104:16, :105:24, :106:15, :108:22, :109:27
  assign wb_ack = wbActive;	// src/main/scala/WishboneSnn.scala:20:7, :92:29
  assign io_spikesOut = spikesOutReg;	// src/main/scala/WishboneSnn.scala:20:7, :78:29
endmodule

